dist: trusty
sudo: true

language: cpp
compiler: gcc
notifications:
    slack: gqcg:13JQ7AAK5DMZPeAInhCMX6YJ
    email: false

# Travis CI's CMake version is only 3.2.2. This is a workaround (https://github.com/travis-ci/travis-ci/issues/7437) that upgrades to a newer version of CMake
before_install:
  - mkdir ${HOME}/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

addons:
  apt:
    packages:
      # My dependencies
      - libboost-test-dev

      # LibInt2 dependencies
      - libboost-dev
      - libgmp-dev

env:
  # If installing LibInt2 in the default, this is where the basis files are found
  # - LIBINT_DATA_PATH=/usr/local/libint/2.2.0/include/libint2/basis

install:
  # Install Eigen3
  - hg clone https://bitbucket.org/eigen/eigen /tmp/eigen
  - mkdir /tmp/eigen-build && cd /tmp/eigen-build
  - cmake . /tmp/eigen -DCMAKE_INSTALL_PREFIX=/opt/local
  - make
  - sudo make install

  # Install LibInt2 (https://github.com/evaleev/libint/wiki)
  #   Configuring the LibInt compiler
  - cd
  - mkdir build_libint && cd build_libint
  - curl -OL "https://github.com/evaleev/libint/archive/v2.2.0.tar.gz"
  - tar -xvzf v2.2.0.tar.gz
  - cd libint-2.2.0
  - ./autogen.sh
  - mkdir build_configure && cd build_configure
  - ../configure
  #   Generating the LibInt library
  - make export
  #   Compiling the LibInt library
  - tar -xvzf libint-2.2.0.tgz
  - cd libint-2.2.0
  # - ./configure
  # - make
  # - sudo make install

script:
  - cd /home/travis/build/lelemmen/libint-wrapper
  - mkdir build && cd build
  - cmake ..
  - make
  - tests/Basis_test
  # - make test
  - sudo make install