# Specify the virtual environment
dist: trusty
sudo: true

# Specify the project language and the compiler to test to
language: cpp
compiler: gcc

# Enable Slack notifications, disable e-mail
notifications:
    slack: gqcg:13JQ7AAK5DMZPeAInhCMX6YJ
    email: false

before_install:
  - tools/install-cmake.sh

# Install packages through APT
addons:
  apt:
    packages:
      - libgmp-dev # libint2 dependency

# Install dependencies
install:
  - tools/install-eigen.sh
  - tools/install-boost.sh
  - tools/install-libint.sh

# Run the build script
script:
  - tools/script.sh
