dist: trusty
sudo: true

language: cpp
compiler: gcc
notifications:
    slack: gqcg:13JQ7AAK5DMZPeAInhCMX6YJ
    email: false

# Travis CI's CMake version is only 3.2.2. This is a workaround (https://github.com/travis-ci/travis-ci/issues/7437) that upgrades to a newer version of CMake
before_install:
  - mkdir ${HOME}/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.9/cmake-3.9.1-Linux-x86_64.sh
  - chmod +x cmake-3.9.1-Linux-x86_64.sh
  - ./cmake-3.9.1-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

addons:
  apt:
    packages:
      # libint2 dependencies
      - libgmp-dev

install:
  # Install Eigen3
  - hg clone https://bitbucket.org/eigen/eigen /tmp/eigen
  - mkdir /tmp/eigen-build && cd /tmp/eigen-build
  - cmake . /tmp/eigen -DCMAKE_INSTALL_PREFIX=/opt/local
  - make
  - sudo make install

  # Install boost
  - cd
  - curl -OL "https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2"
  - cd /usr/local/
  - sudo tar --bzip2 -xf ~/boost_1_65_1.tar.bz2

  # Install libint2 (https://github.com/evaleev/libint/wiki)
  #   Configuring the libint compiler
  - cd
  - mkdir build_libint && cd build_libint
  - curl -OL "https://github.com/evaleev/libint/archive/v2.3.1.tar.gz"
  - tar -xvzf v2.3.1.tar.gz
  - cd libint-2.3.1
  - ./autogen.sh
  - mkdir build_configure && cd build_configure
  - ../configure CXXFLAGS=-I/usr/local/boost_1_65_1
  #   Generating the libint library
  - make export
  #   Compiling the libint library
  - tar -xvzf libint-2.3.1.tgz
  - cd libint-2.3.1
  - ./configure CXXFLAGS=-I/usr/local/boost_1_65_1
  - make
  - sudo make install

script:
  - cd /home/travis/build/lelemmen/libint-wrapper
  - mkdir build && cd build
  - cmake .. -DBOOST_ROOT=/usr/local/boost_1_65_1
  - make && make test && sudo make install
